version: "3.2"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
